version: '16.0'

services:
  database:
    image: postgres:16.0
    environment:
      - POSTGRES_DB=LDCPM
      - POSTGRES_USER=ldcpm
      - POSTGRES_PASSWORD=1234
    ports:
      - 5431:5432
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
    
